/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_stefanlober_mathsmark_calc_fft_NativeFFTCalcElement */

#ifndef _Included_de_stefanlober_mathsmark_calc_fft_NativeFFTCalcElement
#define _Included_de_stefanlober_mathsmark_calc_fft_NativeFFTCalcElement
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     de_stefanlober_mathsmark_calc_fft_NativeFFTCalcElement
 * Method:    internalCalculate
 * Signature: (Ljava/lang/String;[DI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_de_stefanlober_mathsmark_calc_fft_NativeFFTCalcElement_internalCalculate
  (JNIEnv *, jobject, jstring, jdoubleArray, jint);

/*
 * Class:     de_stefanlober_mathsmark_calc_fft_NativeFFTCalcElement
 * Method:    internalInterrupt
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_stefanlober_mathsmark_calc_fft_NativeFFTCalcElement_internalInterrupt
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
